M48
; DRILL file {KiCad 8.0.7} date 2025-08-15T13:24:58-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-15T13:24:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.39Y-1.08
X5.73Y-1.61
X7.5028Y-1.074
X7.5028Y-1.614
M30
